# Generated by Django 4.2.3 on 2024-02-06 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("custom", "0003_alter_academiclevel_id_alter_administrativepost_id_and_more"),
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "firstname",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Naran Propriu"
                    ),
                ),
                (
                    "lastname",
                    models.CharField(max_length=200, null=True, verbose_name="Apelidu"),
                ),
                (
                    "pob",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Fatin Moris",
                    ),
                ),
                (
                    "dob",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data Moris"
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[("Mane", "Mane"), ("Feto", "Feto")],
                        max_length=10,
                        null=True,
                        verbose_name="Sexu",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Enderesu (Aldeia/Bairu)",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Nu. Telemovel",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, null=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="Client")),
                ("datetime", models.DateTimeField(null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "administrativepost",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clientpost",
                        to="custom.administrativepost",
                        verbose_name="Postu administrativu",
                    ),
                ),
                (
                    "municipality",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clientmun",
                        to="custom.municipality",
                        verbose_name="Munisipiu",
                    ),
                ),
                (
                    "user_created",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "village",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clientvillage",
                        to="custom.village",
                        verbose_name="Suku",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pedidu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kodigupedidu",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Kodigu Pedidu",
                    ),
                ),
                ("datapedidu", models.DateField(null=True)),
                ("datasimuprodutu", models.DateField(blank=True, null=True)),
                ("is_sent", models.BooleanField(default=False, null=True)),
                ("is_ontheway", models.BooleanField(default=False, null=True)),
                ("is_delivered", models.BooleanField(default=False, null=True)),
                ("is_recieved", models.BooleanField(default=False, null=True)),
                ("hashed", models.CharField(max_length=32, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clientpedidu",
                        to="client.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PediduProdutu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "totalprodutu",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Total Pedidu"
                    ),
                ),
                (
                    "totalpresu",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Total Presu",
                    ),
                ),
                ("is_checked", models.BooleanField(default=False, null=True)),
                ("is_delivered", models.BooleanField(default=False, null=True)),
                ("is_recieved", models.BooleanField(default=False, null=True)),
                ("hashed", models.CharField(max_length=32, null=True)),
                (
                    "pedidu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pedidu",
                        to="client.pedidu",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.productunit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClientUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clientuser",
                        to="client.client",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clientuser",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
