# Generated by Django 3.2.9 on 2023-06-07 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('custom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=models.UUIDField(default=uuid.uuid4, editable=False), editable=False, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=200, null=True, verbose_name='Naran Propriu')),
                ('lastname', models.CharField(max_length=200, null=True, verbose_name='Apelidu')),
                ('pob', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fatin Moris')),
                ('dob', models.DateTimeField(blank=True, null=True, verbose_name='Data Moris')),
                ('sex', models.CharField(choices=[('Mane', 'Mane'), ('Feto', 'Feto')], max_length=10, null=True, verbose_name='Sexu')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Enderesu (Aldeia/Bairu)')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nu. Telemovel')),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Client')),
                ('datetime', models.DateTimeField(null=True)),
                ('administrativepost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientpost', to='custom.administrativepost', verbose_name='Postu administrativu')),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientmun', to='custom.municipality', verbose_name='Munisipiu')),
                ('user_created', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientvillage', to='custom.village', verbose_name='Suku')),
            ],
        ),
        migrations.CreateModel(
            name='ClientUser',
            fields=[
                ('id', models.UUIDField(default=models.UUIDField(default=uuid.uuid4, editable=False), editable=False, primary_key=True, serialize=False)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clientuser', to='client.client')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clientuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
