# Generated by Django 4.2.3 on 2023-08-28 13:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuser',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
