# Generated by Django 4.2.3 on 2023-08-28 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('client', '0004_alter_clientuser_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numerupakote', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numeru')),
                ('datapedidu', models.DateField(null=True)),
                ('datasimuprodutu', models.DateField(null=True)),
                ('is_sent', models.BooleanField(default=False, null=True)),
                ('is_ontheway', models.BooleanField(default=False, null=True)),
                ('is_recieved', models.BooleanField(default=False, null=True)),
                ('hashed', models.CharField(max_length=32, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientpedidu', to='client.client')),
            ],
        ),
        migrations.CreateModel(
            name='PediduProdutu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalprodutu', models.IntegerField(blank=True, null=True, verbose_name='Total Pedidu')),
                ('is_recieved', models.BooleanField(default=False, null=True)),
                ('hashed', models.CharField(max_length=32, null=True)),
                ('pedidu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidu', to='client.pedidu')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productunit')),
            ],
        ),
    ]
