# Generated by Django 4.2.3 on 2023-08-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_remove_pedidu_numerupakote_pedidu_kodigupedidu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidu',
            name='datasimuprodutu',
            field=models.DateField(blank=True, null=True),
        ),
    ]
