# Generated by Django 4.2.3 on 2023-08-31 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_alter_pedidu_datasimuprodutu'),
    ]

    operations = [
        migrations.AddField(
            model_name='pediduprodutu',
            name='totalpresu',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Presu'),
        ),
    ]
