# Generated by Django 4.2.3 on 2023-08-31 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_pediduprodutu_totalpresu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pediduprodutu',
            name='totalpresu',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Total Presu'),
        ),
    ]
