# Generated by Django 4.2.3 on 2023-11-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsell',
            name='total_out',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Distribui'),
        ),
    ]
