# Generated by Django 4.2.3 on 2023-12-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0002_alter_productsell_total_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsell',
            name='totalprice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total Presu'),
        ),
    ]
