# Generated by Django 4.2.3 on 2024-02-06 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Naran Produtu"
                    ),
                ),
                (
                    "volume",
                    models.CharField(max_length=200, null=True, verbose_name="Volume"),
                ),
                ("is_active", models.BooleanField(default=True, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="Product"),
                ),
                ("datetime", models.DateTimeField(null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "user_created",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductUnit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "unit",
                    models.CharField(max_length=200, null=True, verbose_name="Unidade"),
                ),
                ("is_active", models.BooleanField(default=True, null=True)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, null=True, verbose_name="Presu"
                    ),
                ),
                ("datetime", models.DateTimeField(null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productunit",
                        to="product.product",
                    ),
                ),
                (
                    "user_created",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductUnitStock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "total",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Total Tama"
                    ),
                ),
                (
                    "total_update",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Total Update"
                    ),
                ),
                (
                    "total_update_pedidu",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        verbose_name="Total Update bazeia ba Pedidu",
                    ),
                ),
                (
                    "total_out",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Total Sai"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productstock",
                        to="product.product",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productstock",
                        to="product.productunit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(null=True)),
                (
                    "total_in",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Total Tama"
                    ),
                ),
                (
                    "total_out",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Total Distribui"
                    ),
                ),
                (
                    "total",
                    models.IntegerField(blank=True, null=True, verbose_name="Total"),
                ),
                ("is_confirm", models.BooleanField(default=False, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("hashed", models.CharField(max_length=32, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.productunit",
                    ),
                ),
                (
                    "user_created",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
