# Generated by Django 4.2.3 on 2023-08-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productunitstock',
            name='total_update_pedidu',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Update bazeia ba Pedidu'),
        ),
    ]
