# Generated by Django 4.2.3 on 2023-11-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productunitstock_total_update_pedidu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttransaction',
            name='total_out',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Distribui'),
        ),
        migrations.AlterField(
            model_name='productunitstock',
            name='total_update_pedidu',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Total Update bazeia ba Pedidu'),
        ),
    ]
